Fix issues found by PVS-Studio static analyzer #2
juliusfriedman/net7mma_core pull request #20
Opened 2023-10-24 23:32 UTC by dimhotepus

https://pvs-studio.com/en/order/open-source-license/

2023-10-24 23:40 UTC, juliusfriedman commented on Rtp/RFC3550.cs
> +                    if (packet.BlockCount > 0) using (SourceDescriptionReport asReport = new SourceDescriptionReport(packet, false)) if ((hasCName = asReport.HasCName)) break;
Why drop the check for cName here?

2023-10-24 23:40 UTC, juliusfriedman commented on Rtp/RFC3550.cs
> +                    if (currentPacket.BlockCount > 0) using (SourceDescriptionReport asReport = new SourceDescriptionReport(currentPacket, false)) if ((hasCName = asReport.HasCName)) break;
Why would we drop the check for `hasCName`?

2023-10-24 23:41 UTC, juliusfriedman commented on Rtp/RFC3550.cs
> +            if (amount > byte.MaxValue) throw Common.Binary.CreateOverflowException("amount", amount, byte.MinValue.ToString(), byte.MaxValue.ToString());
This is a good fix by itself. It's a missing throw.

2023-10-24 23:41 UTC, juliusfriedman commented on Rtp/RFC3550.cs
> +            using Media.RFC3550.SourceList sourceList = new RFC3550.SourceList(0);
Good fix

2023-10-24 23:41 UTC, juliusfriedman commented on Rtp/Rtcp/RtcpHeader.cs
> +                if (value > RtcpHeader.MinimumLengthInWords) throw Binary.CreateOverflowException("LengthInWordsMinusOne", value, ushort.MinValue.ToString(), ushort.MaxValue.ToString());
Good fix

2023-10-24 23:41 UTC, juliusfriedman commented on Rtp/Rtcp/RtcpPacket.cs
> +            if (padding < 0 || padding > byte.MaxValue) throw Binary.CreateOverflowException("padding", padding, byte.MinValue.ToString(), byte.MaxValue.ToString());
Good fix.

2023-10-24 23:42 UTC, juliusfriedman commented on Rtp/Rtcp/RtcpReport.cs
> +            if (reportBlock == null) throw new ArgumentNullException("reportBlock");
I don't think I agree with this fix.

2023-10-24 23:42 UTC, juliusfriedman commented on Rtp/Rtcp/SourceDescriptionReport.cs
Good Fix!

2023-10-24 23:42 UTC, juliusfriedman commented on Rtp/Rtcp/SourceDescriptionReport.cs
>                  {
Are the parenthesis that important?

2023-10-24 23:43 UTC, juliusfriedman commented on Rtp/RtpClient.Methods.cs
> +            if (Common.IDisposedExtensions.IsNullOrDisposed(this) || Common.IDisposedExtensions.IsNullOrDisposed(context)  //If the context is disposed
I suppose this is a good fix, the other way was intentionally checking in parallel. but this is good I suppose.

2023-10-24 23:43 UTC, juliusfriedman commented on Rtp/RtpClient.Methods.cs
> +            if (Common.IDisposedExtensions.IsNullOrDisposed(context) || context.SynchronizationSourceIdentifier.Equals(Common.Binary.Zero) || false.Equals(context.IsRtcpEnabled) || context.RemoteRtcp
These are all intentional.

2023-10-24 23:44 UTC, juliusfriedman requested changes
I put my comments on what is intentional vs what is not intentional, please let me know how strongly you feel and I will review again from there.

2023-10-24 23:45 UTC, juliusfriedman commented on Rtp/RFC3550.cs
> +                    if (packet.BlockCount > 0) using (SourceDescriptionReport asReport = new SourceDescriptionReport(packet, false)) if ((hasCName = asReport.HasCName)) break;
I see its a duplicate check.

2023-10-24 23:45 UTC, juliusfriedman commented on Rtp/RFC3550.cs
> +                    if (currentPacket.BlockCount > 0) using (SourceDescriptionReport asReport = new SourceDescriptionReport(currentPacket, false)) if ((hasCName = asReport.HasCName)) break;
I see this is a duplicate check...

2023-10-24 23:51 UTC, juliusfriedman commented on Rtp/Rtcp/RtcpReport.cs
> +            if (reportBlock == null) throw new ArgumentNullException("reportBlock");
After review I see its checked twice...

2023-10-25 00:09 UTC, dimhotepus commented
@juliusfriedman Could you please recheck?

2023-10-25 00:30 UTC, juliusfriedman approved these changes

2023-10-25 00:31 UTC, juliusfriedman commented
Thank you for your contributions!!!

2023-10-25 00:31 UTC, merged