Use pattern matching (semiautomated replacement)
juliusfriedman/net7mma_core pull request #29
Opened 2023-11-13 15:16 UTC by dimhotepus

* ReferenceEquals(X, null) -> x is null.
* == / != null -> is / is not null.
* .Equals(false / 0 / 1) -> is false / 0 / 1.
* .Equals(true) -> .

2023-11-13 23:37 UTC, juliusfriedman requested changes
I got down to Rtsp and had to stop :( I will resume again when I get time. Thank you for your continued contributions!

There should be enough feedback that you can provide the 2nd round of code without my entire review.

Thanks again!

2023-11-13 23:37 UTC, juliusfriedman commented on Concepts/Classes/Threading/Threading.cs
I think that

return ```object.ReferenceEquals(UnderlyingCompressedStack, null) is false``` is false is harder to read than
```return UnderlyingCompressedStack is not null ```

2023-11-13 23:37 UTC, juliusfriedman commented on Concepts/Classes/Threading/Threading.cs
> +                if (object.ReferenceEquals(ExceptionHandler, null) is false &&
```object.ReferenceEquals(ExceptionHandler, null) is false``` is harder to read than it was IMHO, lets use
```ExceptionHandler is not null```

2023-11-13 23:37 UTC, juliusfriedman commented on Concepts/Classes/E/Extensions.cs
>              if (object.ReferenceEquals(this, obj)) return true;
```obj is Extensions e && Equals(e);```

2023-11-13 23:37 UTC, juliusfriedman commented on Concepts/Classes/E/Extensions.cs
> +            if ((obj is Extensions) is false) return false;
See above

2023-11-13 23:37 UTC, juliusfriedman commented on Concepts/Classes/T/T.cs
> +                    return object.ReferenceEquals(__refvalue(*(System.TypedReference*)(Reference.Reference), System.Type), null) is false;
I think this is a little cleaner.
```__refvalue(*(System.TypedReference*)(Reference.Reference), System.Type) is not null```

2023-11-13 23:37 UTC, juliusfriedman commented on Http/HttpContent.cs
> +            if (boundary is null || boundary.Count == 0) throw new ArgumentException("boundary cannot be null or empty");
We miss 0 here, ```boundary.Count is 0```

2023-11-13 23:37 UTC, juliusfriedman commented on Http/HttpContent.cs
We miss Count here ```data.Count is 0```

2023-11-13 23:37 UTC, juliusfriedman commented on Rtp/RtpClient.Constants.cs
> +            if (frameByte.HasValue && buffer[offset++].Equals(frameByte) is false) return -1; //goto ReadLengthOnly;
frameByte.Value

2023-11-13 23:37 UTC, juliusfriedman commented on Rtp/RtpClient.Methods.cs
> +                context.Goodbye is not null &&
If we are going to change this why not use 
```context.Goodbye.?Transferred.HasValue```

2023-11-13 23:37 UTC, juliusfriedman commented on Rtp/RtpClient.Methods.cs
> +            catch { if (Common.IDisposedExtensions.IsNullOrDisposed(this) is false) throw; }
IsNotNullOrDisposed(this) looks cleaner

2023-11-13 23:37 UTC, juliusfriedman commented on Rtp/RtpClient.Methods.cs
> +                if (length > 0 && context.IsActive && sent == 0 && false.Equals(buffers is null))
Hard to read ```false.Equals(buffers is null)``` it is, let us use instead ``` buffers is not null ```

2023-11-13 23:37 UTC, juliusfriedman commented on Rtp/RtpClient.Methods.cs
> +                    c.RtpSocket.Handle == socketHandle) break;
We miss RtcpSocket here. This would be something like 
```
c.RtpSocket is not null &&
                    c.RtpSocket.Handle == socketHandle ||
                    c.RtcpSocket is not null &&
                    c.RtcpSocket.Handle == socketHandle;
                    ```

2023-11-13 23:37 UTC, juliusfriedman commented on Rtp/RtpClient.Methods.cs
> +                    c.RtpSocket.Handle == socketHandle) break;
I think instead of == lets use Equals method here.

2023-11-13 23:37 UTC, juliusfriedman commented on Rtp/RtpClient.Methods.cs
> +            while (m_SignalOffset > 0 && Common.IDisposedExtensions.IsNullOrDisposed(this) is false)
See other comments about IsNotNullOrDisposed, its more readable and consistent?

2023-11-13 23:37 UTC, juliusfriedman commented on Rtp/RtpClient.cs
> +                if (rangeInfo is not null && rangeInfo.Parts.Any())
👍

2023-11-13 23:37 UTC, juliusfriedman commented on Rtp/RtpClient.cs
> +                            rtcpPort ?? (false.Equals(mediaDescription.MediaPort is 0) ? mediaDescription.MediaPort + 1 : mediaDescription.MediaPort)); //RemoteRtcp
lets use instead 

mediaDescription.MediaPort is not 0

2023-11-13 23:37 UTC, juliusfriedman commented on Rtp/RtpClient.cs
> +                if (ssrc.Equals(senderSsrc) && false.Equals(ssrc is 0)) throw new InvalidOperationException("ssrc and senderSsrc must be unique.");
ssrc is not instead of false.Equals

2023-11-13 23:37 UTC, juliusfriedman commented on Rtp/RtpClient.cs
> +            if (false.Equals(partyId is 0) && false.Equals(Common.IDisposedExtensions.IsNullOrDisposed(transportContext)))// && transportContext.InDiscovery)
is not 0 instead of false Equals.

2023-11-13 23:37 UTC, juliusfriedman commented on Rtp/RtpClient.cs
> +            if (action is null || data is null || length.Equals(Common.Binary.Zero)) return;
length is Common.Binary.Zero

2023-11-13 23:37 UTC, juliusfriedman commented on Rtp/RtpFrame.cs
> +                    if (Common.IDisposedExtensions.IsNullOrDisposed(extension) is false && extension.IsComplete)
[System.Runtime.CompilerServices.MethodImpl(System.Runtime.CompilerServices.MethodImplOptions.AggressiveInlining)]
        public static bool IsNotNullOrDisposed(this IDisposed dispose) => IsNullOrDisposed(dispose) is false;

2023-11-13 23:37 UTC, juliusfriedman commented on Rtp/RtpFrame.cs
> +            for (int i = 0 /*false.Equals(Packets is null) && i < Packets.Count*/ ; false.Equals(IsDisposed) && i < Count; ++i) Depacketize(Packets[i]);
`IsDisposed is false`

2023-11-13 23:37 UTC, juliusfriedman commented on Rtsp/RtspClient.cs
> +            foreach (RtspClientAction handler in action.GetInvocationList().Cast<RtspClientAction>())
I think the `Cast` is redundant here, we already unbox / cast in the foreach?

2023-11-13 23:37 UTC, juliusfriedman commented on Rtsp/RtspClient.cs
> +                        if (m_Playing.ContainsKey(context.MediaDescription))
👍

2023-11-13 23:37 UTC, juliusfriedman commented on Rtsp/RtspClient.cs
> +                    if (string.IsNullOrWhiteSpace(realm) is false)
IsNotNullOrWhitespace

2023-11-13 23:37 UTC, juliusfriedman commented on Rtsp/RtspClient.cs
> +                if (string.IsNullOrWhiteSpace(cnonce) is false)
See other comments use IsNotNullOrEmpty etc.

2023-11-13 23:37 UTC, juliusfriedman commented on Rtsp/RtspClient.cs
> +                                if (AutomaticallyReconnect && Common.IDisposedExtensions.IsNullOrDisposed(this) is false)
IsNotNullOrDisposed.

2023-11-13 23:37 UTC, juliusfriedman commented on Rtsp/RtspClient.cs
> +                                if ((string.IsNullOrWhiteSpace(contentBase = response[RtspHeaders.ContentBase]) is false ||
IsNot functions

2023-11-14 16:23 UTC, dimhotepus commented on Rtp/RtpClient.Methods.cs
> +                    c.RtpSocket.Handle == socketHandle) break;
They are `nint`.

2023-11-14 16:26 UTC, dimhotepus commented on Rtp/RtpFrame.cs
> +                    if (Common.IDisposedExtensions.IsNullOrDisposed(extension) is false && extension.IsComplete)
Comment about negative methods above.

2023-11-14 16:28 UTC, dimhotepus commented on Rtsp/RtspClient.cs
> +            foreach (RtspClientAction handler in action.GetInvocationList().Cast<RtspClientAction>())
Yep, foreach performs cast, but direct Cast is more clear and have better exception in case of failure.

2023-11-14 22:14 UTC, juliusfriedman requested changes
Overall looks pretty good, just a few things to fix to be consistent.

I would prefer if we use the Negative methods e.g. IsNotNullOrDisposed but I can take care of that in a separate commit afterwards if you prefer.

I think the main thing in this PR to finish is false.Equals removal, it seems you left it in a bunch of places where its can trivially be removed and looks better without (use is not instead)

Almost there, please let me know when you want me to to take another look or if you need any help!

Thank you for your continued contributions!

2023-11-14 22:14 UTC, juliusfriedman commented on Codecs/Audio/Flac/FlacReader.cs
> +            else if ((x & 0xC0) != 0 && (x & 0x20) is 0)
is not 0 for !=

2023-11-14 22:14 UTC, juliusfriedman commented on Common/Classes/PacketBase.cs
> +            get { return Common.IDisposedExtensions.IsNullOrDisposed(Holding) is false; }
IsNotNullOrDisposed?

2023-11-14 22:14 UTC, juliusfriedman commented on Containers/BaseMedia/BaseMediaReader.cs
>                                                          if (-2 == waveFormatId)
waveFormatId is -2 ?

2023-11-14 22:14 UTC, juliusfriedman commented on Containers/BaseMedia/BaseMediaReader.cs
>                                                          //else 16 more if version == 1
is

2023-11-14 22:14 UTC, juliusfriedman commented on Rtp/Rtcp/RtcpPacket.cs
> +            if (m_OwnsHeader && Common.IDisposedExtensions.IsNullOrDisposed(Header) is false)
I think using IsNotNullOrDisposed here looks cleaner.

2023-11-14 22:14 UTC, juliusfriedman commented on Rtp/RtpClient.Methods.cs
> +                if (Common.IDisposedExtensions.IsNullOrDisposed(tc) is false &&
IsNullOrDisposed(tc) is false is harder to read than IsNotNullorDisposed(tc)

2023-11-14 22:14 UTC, juliusfriedman commented on Rtp/RtpClient.Methods.cs
> +                || false.Equals(context.Goodbye is null)) return false; //No reports can be sent.
context.Goodbye is not null is easier to read.

2023-11-14 22:14 UTC, juliusfriedman commented on Rtp/RtpClient.Methods.cs
> +                Common.IDisposedExtensions.IsNullOrDisposed(this) is false)
IsNotNullOrDisposed looks cleaner IMHO

2023-11-14 22:14 UTC, juliusfriedman commented on Rtp/RtpClient.Methods.cs
> +            while (Common.IDisposedExtensions.IsNullOrDisposed(m_Buffer) is false &&
IsNotNullOrDisposed looks cleaner IMHO

2023-11-14 22:14 UTC, juliusfriedman commented on Rtp/RtpClient.cs
> +                        if (LocalRtcp is not null && false.Equals(RtcpSocket.IsBound)) RtcpSocket.Bind(LocalRtcp);
is false

2023-11-14 22:14 UTC, juliusfriedman commented on Rtp/RtpClient.cs
> +                        if (RemoteRtcp is not null && false.Equals(RtcpSocket.Connected))
is false.

2023-11-14 22:14 UTC, juliusfriedman commented on Rtp/RtpClient.cs
> +                    if (Common.IDisposedExtensions.IsNullOrDisposed(transportContext.ReceiversReport) is false &&
IsNotNullorDisposed looks better here.

2023-11-14 22:14 UTC, juliusfriedman commented on Rtp/RtpClient.cs
> +                    else if (Common.IDisposedExtensions.IsNullOrDisposed(transportContext.SendersReport) is false &&
IsNotNullOrDisposed.

2023-11-14 22:14 UTC, juliusfriedman commented on Rtp/RtpFrame.cs
> +                    if (Common.IDisposedExtensions.IsNullOrDisposed(extension) is false && extension.IsComplete)
I must have missed it, FYI I already added IsNotNullOrDisposed and it looks cleaner IMHO, putting `is false` everywhere just wastes more characters and since we have the same logic being performed more than once we should have a function for it anyway.

2023-11-14 22:14 UTC, juliusfriedman commented on Rtp/RtpFrame.cs
> +            for (int i = 0 /*false.Equals(Packets is null) && i < Packets.Count*/ ; IsDisposed is false && i < Count; ++i) Depacketize(Packets[i]);
Its a comment but 

`false.Equals(Packets is null)` is the same as
`Packets is not null`

2023-11-14 22:14 UTC, juliusfriedman commented on Rtp/RtpPacket.cs
> +                return Common.IDisposedExtensions.IsNullOrDisposed(extension) is false
IsNotNullOrDiposed.

2023-11-14 22:14 UTC, juliusfriedman commented on Rtsp/RtspClient.cs
> +            if(Common.IDisposedExtensions.IsNullOrDisposed(this) is false) m_RtpClient.Activate();
IsNotNullOrDisposed looks better.

2023-11-14 22:14 UTC, juliusfriedman commented on Rtsp/RtspClient.cs
> +            if (Common.IDisposedExtensions.IsNullOrDisposed(this) is false) OnPlaying();
is false vs IsNotNullOrDisposed.

2023-11-14 22:14 UTC, juliusfriedman commented on Rtsp/RtspClient.cs
> +                    if (string.IsNullOrWhiteSpace(realm) is false)
You don't seem to like the negative methods?

2023-11-14 22:14 UTC, juliusfriedman commented on Rtsp/RtspClient.cs
> +                                if (Common.IDisposedExtensions.IsNullOrDisposed(this) is false)
Common.IDisposedExtensions.IsNotNullOrDisposed(this) looks better.

2023-11-14 22:14 UTC, juliusfriedman commented on Rtsp/RtspMessage.cs
> +            if (offset > message.Length) throw new ArgumentOutOfRangeException(nameof(offset));
offset < 0? I think we check the same thing below, not sure if thats what you meant to do was add the 0 case or not.

2023-11-14 22:14 UTC, juliusfriedman commented on RtspServer/ClientSession.cs
> +                    if (Common.IDisposedExtensions.IsNullOrDisposed(lastContext) is false)
```Common.IDisposedExtensions.IsNullOrDisposed(lastContext) is false``` is longer than ```Common.IDisposedExtensions.IsNotNullOrDisposed(lastContext)```

2023-11-14 22:14 UTC, juliusfriedman commented on RtspServer/ClientSession.cs
> +        internal Common.Collections.Generic.ConcurrentThesaurus<int, RtpPacket> PacketBuffer = new();
readonly.

2023-11-14 22:14 UTC, juliusfriedman commented on Rtp/RtpClient.Methods.cs
> +                                if (receivedRtp is 0 || false.Equals(lastError == System.Net.Sockets.SocketError.Success))
lastError is not System.Net.Sockets.SocketError.Success

2023-11-15 14:17 UTC, juliusfriedman commented on Common/Extensions/StreamExtensions.cs
> +                if (e is not null && e is TransactionBase)
e is TransactionBase tb

2023-11-15 14:17 UTC, juliusfriedman commented on Common/Extensions/StreamExtensions.cs
> +                if (e is not null && e is TransactionBase)
e is TransactionBase tb

2023-11-15 14:18 UTC, juliusfriedman commented on Common/Extensions/StreamExtensions.cs
> +                if (e is not null && e is TransactionBase)
e is TransactionBase tb

2023-11-15 20:16 UTC, juliusfriedman commented
Here are a few replacements I found useful..

false\.Equals\((\w*)\) -> $1 is false
\.Equals\(false\) -> is false
[oO]bject\.ReferenceEquals\((.*),\s(\w*)\) ->$1 is null
[oO]bject\.ReferenceEquals\((.*),\s(\w*)\)\.Equals\(false\) ->$1 is not null

2023-11-15 22:08 UTC, juliusfriedman commented
I merged in a bunch of QOL improvements, if you still think this is necessary please rebase and make another PR.

2023-11-16 13:18 UTC, juliusfriedman commented
Here are some better patterns

```
false\.Equals\(([^\)]+)\)
```

This will leave a few ``` is null is false ``` which can be easily replaced with ```is not null```

Overall I like the pattern matched versions better because they seem easier to read.

Let me know if your still interested in doing this!

Thanks for your feedback and continued interest!

2023-11-17 19:52 UTC, juliusfriedman commented
```false\.Equals\((\w+)\s=+\snull\)``` looking explicitly for null is also pretty safe and allows you to easily replaced with ```is not null``

2023-11-17 23:36 UTC, juliusfriedman commented
I pushed up some more safer commits and fixed a few statements which were missed as well as a few minor bugs.

There is still plenty of old style ```false.Equals``` but I compared it with ```is false``` and there is basically no difference in the x86 once optomized.

This is still good to have as it makes the code much clearer to read, let me know if you want to rebase this or not I will keep plugging away in the meantime.

2023-11-18 16:13 UTC, juliusfriedman commented
I got a lot these with recent commits, if you don't mind to rebase this we can continue the process with what you find after that.

Thanks again for your contributions!

2023-11-19 02:35 UTC, juliusfriedman commented
I am leaving the code where it is for now until you report back, the main thing I would like to be consistent on is the use of 

is and is not vs

2023-11-19 14:05 UTC, juliusfriedman commented on Rtp/Rtcp/RtcpPacket.cs
> +            if (m_OwnsHeader && Common.IDisposedExtensions.IsNullOrDisposed(Header) is false)
Besides the naming, I like IsNotNullOrDiposed better, after everything is done I might make a few more extension methods, AreAnyNullOrDisposed(params), AreAllNullOrDiposed(params) and refactor some places to use them depending on how benchmarking goes.

2023-11-21 05:48 UTC, juliusfriedman commented
I finished up my regressions, I will try to rebase this entire commit tomorrow.

Thanks again for your help and contributions!

2023-11-21 05:58 UTC, juliusfriedman commented on Sdp/MediaDescription.cs
> +            return b is null ? a is null : a.MediaDescriptionLine.Equals(b);
Since b is checked to be not null I think this needs a little revision

```
return b is null ? a is null : b.Equals(a.MediaDescriptionLine);
```

2023-11-21 06:21 UTC, juliusfriedman commented on Rtsp/RtspMessage.cs
> +            return b is null ? a is null : a.Equals(b);
b.Equals(a) since b is not null.

2023-11-21 15:33 UTC, juliusfriedman commented
I have to make an appointment in about an hour, if I don't get this rebased before then I will finish it up when I come back!

2023-11-21 15:55 UTC, juliusfriedman commented
You removed unchecked in a few places, the default is unchecked :) I put those there so if a checked build was being ran those blocks would still be unchecked. I don't think its likely counters will overflow so I will keep them without the unchecked for now.

2023-11-21 18:04 UTC, merged

2023-11-21 18:05 UTC, juliusfriedman commented
I merged this PR, thanks for your contributions!

I just need to clean up TestServerAsync so it works as expected but other than that LGTM.

2023-11-21 18:05 UTC, juliusfriedman commented
Thanks again for your contributions!